export const config = {
	ERROR: {
		AUTH: {
			UNAUTHORIZED: "Unauthorized",
			INVALID_TOKEN: "Invalid token",
			REGISTRATION_VALIDATION_FAILED: "Registration validation failed",
			LOGIN_VALIDATION_FAILED: "Login validation failed",
			PASSWORD_UPDATE_VALIDATION_FAILED: "Password update validation failed",
			FIRST_NAME_LAST_NAME_REQUIRED: "First name and last name are required",
			INVALID_ORGANIZATION_ID_FORMAT: "Invalid organization ID format",
			ORGANIZATION_NOT_FOUND: "Organization not found",
			USER_ALREADY_EXISTS: "User already exists",
			ERROR_DURING_REGISTRATION: "Error during registration",
			INVALID_CREDENTIALS: "Invalid credentials",
			ERROR_DURING_LOGIN: "Error during login",
			USER_ID_PASSWORD_REQUIRED: "User ID and new password are required",
			PASSWORD_MIN_LENGTH: "Password must be at least 6 characters long",
			ERROR_UPDATING_PASSWORD: "Error updating password",
			USER_NOT_FOUND: "User not found",
			FAILED_TO_CREATE_OR_FIND_PERSON: "Failed to create or find person",
		},
		TEMPLATE: {
			VALIDATION_FAILED: "Template validation failed",
			INVALID_ID_FORMAT: "Invalid template ID format",
			NOT_FOUND: "Template not found",
			CREATE_FAILED: "Error creating template",
			UPDATE_FAILED: "Error updating template",
			DELETE_FAILED: "Error deleting template",
			GET_FAILED: "Error getting template",
			GET_ALL_FAILED: "Error getting templates",
			ERROR_GETTING: "Error getting template",
			ERROR_UPDATING: "Error updating template",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		QUERY_PARAMS: {
			MISSING_ID: "ID parameter is required",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate must be a string",
			INVALID_PAGE: "Invalid page",
			INVALID_LIMIT: "Invalid limit",
			INVALID_ORDER: "Invalid order",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
			INVALID_SORT: "Invalid sort",
			SORT_MUST_BE_STRING: "Sort must be a string",
			INVALID_FILTER: "Invalid filter",
			FILTER_MUST_BE_STRING: "Filter must be a string",
			INVALID_QUERY: "Invalid query",
			QUERY_MUST_BE_STRING: "Query must be a string",
			INVALID_DOCUMENT: "Invalid document",
			DOCUMENT_MUST_BE_STRING: "Document must be a string",
			INVALID_PAGINATION: "Invalid pagination",
			PAGINATION_MUST_BE_STRING: "Pagination must be a string",
			INVALID_COUNT: "Invalid count",
			COUNT_MUST_BE_STRING: "Count must be a string",
			INVALID_GROUPBY: "Invalid groupBy",
			INVALID_COMBINATION: "Invalid combination",
		},
		COMMON: {
			INTERNAL_SERVER_ERROR: "Internal server error",
			VALIDATION_ERROR: "Validation error",
			NOT_FOUND: "Resource not found",
			UNAUTHORIZED: "Unauthorized access",
			NO_UPDATE_FIELDS: "No fields provided for update",
		},
		PRODUCTS: {
			VALIDATION_FAILED: "Products validation failed",
			INVALID_ID_FORMAT: "Invalid products ID format",
			NOT_FOUND: "Products not found",
			CREATE_FAILED: "Error creating products",
			UPDATE_FAILED: "Error updating products",
			DELETE_FAILED: "Error deleting products",
			GET_FAILED: "Error getting products",
			GET_ALL_FAILED: "Error getting products",
			ERROR_GETTING: "Error getting products",
			ERROR_UPDATING: "Error updating products",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		PURCHASE: {
			VALIDATION_FAILED: "Purchase validation failed",
			INVALID_ID_FORMAT: "Invalid purchase ID format",
			NOT_FOUND: "Purchase not found",
			CREATE_FAILED: "Error creating purchase",
			UPDATE_FAILED: "Error updating purchase",
			DELETE_FAILED: "Error deleting purchase",
			GET_FAILED: "Error getting purchase",
			GET_ALL_FAILED: "Error getting purchases",
			ERROR_GETTING: "Error getting purchase",
			ERROR_UPDATING: "Error updating purchase",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		CATEGORY: {
			VALIDATION_FAILED: "Category validation failed",
			INVALID_ID_FORMAT: "Invalid category ID format",
			NOT_FOUND: "Category not found",
			CREATE_FAILED: "Error creating category",
			UPDATE_FAILED: "Error updating category",
			DELETE_FAILED: "Error deleting category",
			GET_FAILED: "Error getting category",
			GET_ALL_FAILED: "Error getting categorys",
			ERROR_GETTING: "Error getting category",
			ERROR_UPDATING: "Error updating category",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		WISHLISTITEM: {
			VALIDATION_FAILED: "WishlistItem validation failed",
			INVALID_ID_FORMAT: "Invalid wishlistitem ID format",
			NOT_FOUND: "WishlistItem not found",
			CREATE_FAILED: "Error creating wishlistitem",
			UPDATE_FAILED: "Error updating wishlistitem",
			DELETE_FAILED: "Error deleting wishlistitem",
			GET_FAILED: "Error getting wishlistitem",
			GET_ALL_FAILED: "Error getting wishlistitems",
			ERROR_GETTING: "Error getting wishlistitem",
			ERROR_UPDATING: "Error updating wishlistitem",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		CARTITEM: {
			VALIDATION_FAILED: "CartItem validation failed",
			INVALID_ID_FORMAT: "Invalid cartitem ID format",
			NOT_FOUND: "CartItem not found",
			CREATE_FAILED: "Error creating cartitem",
			UPDATE_FAILED: "Error updating cartitem",
			DELETE_FAILED: "Error deleting cartitem",
			GET_FAILED: "Error getting cartitem",
			GET_ALL_FAILED: "Error getting cartitems",
			ERROR_GETTING: "Error getting cartitem",
			ERROR_UPDATING: "Error updating cartitem",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		ORDER: {
			VALIDATION_FAILED: "Order validation failed",
			INVALID_ID_FORMAT: "Invalid order ID format",
			NOT_FOUND: "Order not found",
			CREATE_FAILED: "Error creating order",
			UPDATE_FAILED: "Error updating order",
			DELETE_FAILED: "Error deleting order",
			GET_FAILED: "Error getting order",
			GET_ALL_FAILED: "Error getting orders",
			ERROR_GETTING: "Error getting order",
			ERROR_UPDATING: "Error updating order",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		ORDERITEM: {
			VALIDATION_FAILED: "OrderItem validation failed",
			INVALID_ID_FORMAT: "Invalid orderitem ID format",
			NOT_FOUND: "OrderItem not found",
			CREATE_FAILED: "Error creating orderitem",
			UPDATE_FAILED: "Error updating orderitem",
			DELETE_FAILED: "Error deleting orderitem",
			GET_FAILED: "Error getting orderitem",
			GET_ALL_FAILED: "Error getting orderitems",
			ERROR_GETTING: "Error getting orderitem",
			ERROR_UPDATING: "Error updating orderitem",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		VENDOR: {
			VALIDATION_FAILED: "Vendor validation failed",
			INVALID_ID_FORMAT: "Invalid vendor ID format",
			NOT_FOUND: "Vendor not found",
			CREATE_FAILED: "Error creating vendor",
			UPDATE_FAILED: "Error updating vendor",
			DELETE_FAILED: "Error deleting vendor",
			GET_FAILED: "Error getting vendor",
			GET_ALL_FAILED: "Error getting vendors",
			ERROR_GETTING: "Error getting vendor",
			ERROR_UPDATING: "Error updating vendor",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		INSTALLMENT: {
			VALIDATION_FAILED: "Installment validation failed",
			INVALID_ID_FORMAT: "Invalid installment ID format",
			NOT_FOUND: "Installment not found",
			CREATE_FAILED: "Error creating installment",
			UPDATE_FAILED: "Error updating installment",
			DELETE_FAILED: "Error deleting installment",
			GET_FAILED: "Error getting installment",
			GET_ALL_FAILED: "Error getting installments",
			ERROR_GETTING: "Error getting installment",
			ERROR_UPDATING: "Error updating installment",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		NOTIFICATION: {
			VALIDATION_FAILED: "Notification validation failed",
			INVALID_ID_FORMAT: "Invalid notification ID format",
			NOT_FOUND: "Notification not found",
			CREATE_FAILED: "Error creating notification",
			UPDATE_FAILED: "Error updating notification",
			DELETE_FAILED: "Error deleting notification",
			GET_FAILED: "Error getting notification",
			GET_ALL_FAILED: "Error getting notifications",
			ERROR_GETTING: "Error getting notification",
			ERROR_UPDATING: "Error updating notification",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
	},

	SUCCESS: {
		AUTH: {
			REGISTRATION_SUCCESSFUL: "Registration successful",
			LOGGED_IN_SUCCESSFULLY: "Logged in successfully",
			PASSWORD_UPDATED_SUCCESSFULLY: "Password updated successfully",
			USER_CREATED: "User created successfully",
			TOKEN_GENERATED: "Token generated successfully",
			ORGANIZATION_VERIFIED: "Organization verified successfully",
			USER_LOGGED_IN: "User logged in successfully",
		},
		TEMPLATE: {
			CREATED: "Template created successfully",
			UPDATED: "Template updated successfully",
			DELETED: "Template deleted successfully",
			RETRIEVED: "Template retrieved successfully",
			RETRIEVED_ALL: "Templates retrieved successfully",
			GETTING_BY_ID: "Getting template by ID",
		},
		COMMON: {
			OPERATION_SUCCESSFUL: "Operation completed successfully",
		},
		PRODUCTS: {
			CREATED: "Products created successfully",
			UPDATED: "Products updated successfully",
			DELETED: "Products deleted successfully",
			RETRIEVED: "Products retrieved successfully",
			RETRIEVED_ALL: "Productss retrieved successfully",
			GETTING_BY_ID: "Getting products by ID",
		},
		PURCHASE: {
			CREATED: "Purchase created successfully",
			UPDATED: "Purchase updated successfully",
			DELETED: "Purchase deleted successfully",
			RETRIEVED: "Purchase retrieved successfully",
			RETRIEVED_ALL: "Purchases retrieved successfully",
			GETTING_BY_ID: "Getting purchase by ID",
		},
		CATEGORY: {
			CREATED: "Category created successfully",
			UPDATED: "Category updated successfully",
			DELETED: "Category deleted successfully",
			RETRIEVED: "Category retrieved successfully",
			RETRIEVED_ALL: "Categorys retrieved successfully",
			GETTING_BY_ID: "Getting category by ID",
		},
		WISHLISTITEM: {
			CREATED: "WishlistItem created successfully",
			UPDATED: "WishlistItem updated successfully",
			DELETED: "WishlistItem deleted successfully",
			RETRIEVED: "WishlistItem retrieved successfully",
			RETRIEVED_ALL: "WishlistItems retrieved successfully",
			GETTING_BY_ID: "Getting wishlistitem by ID",
		},
		CARTITEM: {
			CREATED: "CartItem created successfully",
			UPDATED: "CartItem updated successfully",
			DELETED: "CartItem deleted successfully",
			RETRIEVED: "CartItem retrieved successfully",
			RETRIEVED_ALL: "CartItems retrieved successfully",
			GETTING_BY_ID: "Getting cartitem by ID",
		},
		ORDER: {
			CREATED: "Order created successfully",
			UPDATED: "Order updated successfully",
			DELETED: "Order deleted successfully",
			RETRIEVED: "Order retrieved successfully",
			RETRIEVED_ALL: "Orders retrieved successfully",
			GETTING_BY_ID: "Getting order by ID",
		},
		ORDERITEM: {
			CREATED: "OrderItem created successfully",
			UPDATED: "OrderItem updated successfully",
			DELETED: "OrderItem deleted successfully",
			RETRIEVED: "OrderItem retrieved successfully",
			RETRIEVED_ALL: "OrderItems retrieved successfully",
			GETTING_BY_ID: "Getting orderitem by ID",
		},
		VENDOR: {
			CREATED: "Vendor created successfully",
			UPDATED: "Vendor updated successfully",
			DELETED: "Vendor deleted successfully",
			RETRIEVED: "Vendor retrieved successfully",
			RETRIEVED_ALL: "Vendors retrieved successfully",
			GETTING_BY_ID: "Getting vendor by ID",
		},
		INSTALLMENT: {
			CREATED: "Installment created successfully",
			UPDATED: "Installment updated successfully",
			DELETED: "Installment deleted successfully",
			RETRIEVED: "Installment retrieved successfully",
			RETRIEVED_ALL: "Installments retrieved successfully",
			GETTING_BY_ID: "Getting installment by ID",
		},
		NOTIFICATION: {
			CREATED: "Notification created successfully",
			UPDATED: "Notification updated successfully",
			DELETED: "Notification deleted successfully",
			RETRIEVED: "Notification retrieved successfully",
			RETRIEVED_ALL: "Notifications retrieved successfully",
			GETTING_BY_ID: "Getting notification by ID",
		},
	},

	ACTIVITY_LOG: {
		NOTIFICATION: {
			ACTIONS: {
				CREATE_NOTIFICATION: "CREATE_NOTIFICATION",
				GET_ALL_NOTIFICATION: "GET_ALL_NOTIFICATION",
				GET_NOTIFICATION: "GET_NOTIFICATION",
				UPDATE_NOTIFICATION: "UPDATE_NOTIFICATION",
				DELETE_NOTIFICATION: "DELETE_NOTIFICATION",
			},
			DESCRIPTIONS: {
				NOTIFICATION_CREATED: "Created new notification",
				NOTIFICATION_UPDATED: "Updated notification",
				NOTIFICATION_DELETED: "Deleted notification",
				NOTIFICATION_RETRIEVED: "Retrieved notification details",
				NOTIFICATIONS_RETRIEVED: "Retrieved notification list",
			},
			PAGES: {
				NOTIFICATION_CREATION: "Notification Creation",
				NOTIFICATION_UPDATE: "Notification Update",
				NOTIFICATION_DELETION: "Notification Deletion",
				NOTIFICATION_DETAILS: "Notification Details",
				NOTIFICATION_LIST: "Notification List",
			},
		},
		INSTALLMENT: {
			ACTIONS: {
				CREATE_INSTALLMENT: "CREATE_INSTALLMENT",
				GET_ALL_INSTALLMENT: "GET_ALL_INSTALLMENT",
				GET_INSTALLMENT: "GET_INSTALLMENT",
				UPDATE_INSTALLMENT: "UPDATE_INSTALLMENT",
				DELETE_INSTALLMENT: "DELETE_INSTALLMENT",
			},
			DESCRIPTIONS: {
				INSTALLMENT_CREATED: "Created new installment",
				INSTALLMENT_UPDATED: "Updated installment",
				INSTALLMENT_DELETED: "Deleted installment",
				INSTALLMENT_RETRIEVED: "Retrieved installment details",
				INSTALLMENTS_RETRIEVED: "Retrieved installment list",
			},
			PAGES: {
				INSTALLMENT_CREATION: "Installment Creation",
				INSTALLMENT_UPDATE: "Installment Update",
				INSTALLMENT_DELETION: "Installment Deletion",
				INSTALLMENT_DETAILS: "Installment Details",
				INSTALLMENT_LIST: "Installment List",
			},
		},
		VENDOR: {
			ACTIONS: {
				CREATE_VENDOR: "CREATE_VENDOR",
				GET_ALL_VENDOR: "GET_ALL_VENDOR",
				GET_VENDOR: "GET_VENDOR",
				UPDATE_VENDOR: "UPDATE_VENDOR",
				DELETE_VENDOR: "DELETE_VENDOR",
			},
			DESCRIPTIONS: {
				VENDOR_CREATED: "Created new vendor",
				VENDOR_UPDATED: "Updated vendor",
				VENDOR_DELETED: "Deleted vendor",
				VENDOR_RETRIEVED: "Retrieved vendor details",
				VENDORS_RETRIEVED: "Retrieved vendor list",
			},
			PAGES: {
				VENDOR_CREATION: "Vendor Creation",
				VENDOR_UPDATE: "Vendor Update",
				VENDOR_DELETION: "Vendor Deletion",
				VENDOR_DETAILS: "Vendor Details",
				VENDOR_LIST: "Vendor List",
			},
		},
		ORDERITEM: {
			ACTIONS: {
				CREATE_ORDERITEM: "CREATE_ORDERITEM",
				GET_ALL_ORDERITEM: "GET_ALL_ORDERITEM",
				GET_ORDERITEM: "GET_ORDERITEM",
				UPDATE_ORDERITEM: "UPDATE_ORDERITEM",
				DELETE_ORDERITEM: "DELETE_ORDERITEM",
			},
			DESCRIPTIONS: {
				ORDERITEM_CREATED: "Created new orderitem",
				ORDERITEM_UPDATED: "Updated orderitem",
				ORDERITEM_DELETED: "Deleted orderitem",
				ORDERITEM_RETRIEVED: "Retrieved orderitem details",
				ORDERITEMS_RETRIEVED: "Retrieved orderitem list",
			},
			PAGES: {
				ORDERITEM_CREATION: "OrderItem Creation",
				ORDERITEM_UPDATE: "OrderItem Update",
				ORDERITEM_DELETION: "OrderItem Deletion",
				ORDERITEM_DETAILS: "OrderItem Details",
				ORDERITEM_LIST: "OrderItem List",
			},
		},
		ORDER: {
			ACTIONS: {
				CREATE_ORDER: "CREATE_ORDER",
				GET_ALL_ORDER: "GET_ALL_ORDER",
				GET_ORDER: "GET_ORDER",
				UPDATE_ORDER: "UPDATE_ORDER",
				DELETE_ORDER: "DELETE_ORDER",
			},
			DESCRIPTIONS: {
				ORDER_CREATED: "Created new order",
				ORDER_UPDATED: "Updated order",
				ORDER_DELETED: "Deleted order",
				ORDER_RETRIEVED: "Retrieved order details",
				ORDERS_RETRIEVED: "Retrieved order list",
			},
			PAGES: {
				ORDER_CREATION: "Order Creation",
				ORDER_UPDATE: "Order Update",
				ORDER_DELETION: "Order Deletion",
				ORDER_DETAILS: "Order Details",
				ORDER_LIST: "Order List",
			},
		},
		CARTITEM: {
			ACTIONS: {
				CREATE_CARTITEM: "CREATE_CARTITEM",
				GET_ALL_CARTITEM: "GET_ALL_CARTITEM",
				GET_CARTITEM: "GET_CARTITEM",
				UPDATE_CARTITEM: "UPDATE_CARTITEM",
				DELETE_CARTITEM: "DELETE_CARTITEM",
			},
			DESCRIPTIONS: {
				CARTITEM_CREATED: "Created new cartitem",
				CARTITEM_UPDATED: "Updated cartitem",
				CARTITEM_DELETED: "Deleted cartitem",
				CARTITEM_RETRIEVED: "Retrieved cartitem details",
				CARTITEMS_RETRIEVED: "Retrieved cartitem list",
			},
			PAGES: {
				CARTITEM_CREATION: "CartItem Creation",
				CARTITEM_UPDATE: "CartItem Update",
				CARTITEM_DELETION: "CartItem Deletion",
				CARTITEM_DETAILS: "CartItem Details",
				CARTITEM_LIST: "CartItem List",
			},
		},
		WISHLISTITEM: {
			ACTIONS: {
				CREATE_WISHLISTITEM: "CREATE_WISHLISTITEM",
				GET_ALL_WISHLISTITEM: "GET_ALL_WISHLISTITEM",
				GET_WISHLISTITEM: "GET_WISHLISTITEM",
				UPDATE_WISHLISTITEM: "UPDATE_WISHLISTITEM",
				DELETE_WISHLISTITEM: "DELETE_WISHLISTITEM",
			},
			DESCRIPTIONS: {
				WISHLISTITEM_CREATED: "Created new wishlistitem",
				WISHLISTITEM_UPDATED: "Updated wishlistitem",
				WISHLISTITEM_DELETED: "Deleted wishlistitem",
				WISHLISTITEM_RETRIEVED: "Retrieved wishlistitem details",
				WISHLISTITEMS_RETRIEVED: "Retrieved wishlistitem list",
			},
			PAGES: {
				WISHLISTITEM_CREATION: "WishlistItem Creation",
				WISHLISTITEM_UPDATE: "WishlistItem Update",
				WISHLISTITEM_DELETION: "WishlistItem Deletion",
				WISHLISTITEM_DETAILS: "WishlistItem Details",
				WISHLISTITEM_LIST: "WishlistItem List",
			},
		},
		CATEGORY: {
			ACTIONS: {
				CREATE_CATEGORY: "CREATE_CATEGORY",
				GET_ALL_CATEGORY: "GET_ALL_CATEGORY",
				GET_CATEGORY: "GET_CATEGORY",
				UPDATE_CATEGORY: "UPDATE_CATEGORY",
				DELETE_CATEGORY: "DELETE_CATEGORY",
			},
			DESCRIPTIONS: {
				CATEGORY_CREATED: "Created new category",
				CATEGORY_UPDATED: "Updated category",
				CATEGORY_DELETED: "Deleted category",
				CATEGORY_RETRIEVED: "Retrieved category details",
				CATEGORYS_RETRIEVED: "Retrieved category list",
			},
			PAGES: {
				CATEGORY_CREATION: "Category Creation",
				CATEGORY_UPDATE: "Category Update",
				CATEGORY_DELETION: "Category Deletion",
				CATEGORY_DETAILS: "Category Details",
				CATEGORY_LIST: "Category List",
			},
		},
		PURCHASE: {
			ACTIONS: {
				CREATE_PURCHASE: "CREATE_PURCHASE",
				GET_ALL_PURCHASE: "GET_ALL_PURCHASE",
				GET_PURCHASE: "GET_PURCHASE",
				UPDATE_PURCHASE: "UPDATE_PURCHASE",
				DELETE_PURCHASE: "DELETE_PURCHASE",
			},
			DESCRIPTIONS: {
				PURCHASE_CREATED: "Created new purchase",
				PURCHASE_UPDATED: "Updated purchase",
				PURCHASE_DELETED: "Deleted purchase",
				PURCHASE_RETRIEVED: "Retrieved purchase details",
				PURCHASES_RETRIEVED: "Retrieved purchase list",
			},
			PAGES: {
				PURCHASE_CREATION: "Purchase Creation",
				PURCHASE_UPDATE: "Purchase Update",
				PURCHASE_DELETION: "Purchase Deletion",
				PURCHASE_DETAILS: "Purchase Details",
				PURCHASE_LIST: "Purchase List",
			},
		},
		PRODUCTS: {
			ACTIONS: {
				CREATE_PRODUCTS: "CREATE_PRODUCTS",
				GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
				GET_PRODUCTS: "GET_PRODUCTS",
				UPDATE_PRODUCTS: "UPDATE_PRODUCTS",
				DELETE_PRODUCTS: "DELETE_PRODUCTS",
			},
			DESCRIPTIONS: {
				PRODUCTS_CREATED: "Created new products",
				PRODUCTS_UPDATED: "Updated products",
				PRODUCTS_DELETED: "Deleted products",
				PRODUCTS_RETRIEVED: "Retrieved products details",
				PRODUCTSS_RETRIEVED: "Retrieved products list",
			},
			PAGES: {
				PRODUCTS_CREATION: "Products Creation",
				PRODUCTS_UPDATE: "Products Update",
				PRODUCTS_DELETION: "Products Deletion",
				PRODUCTS_DETAILS: "Products Details",
				PRODUCTS_LIST: "Products List",
			},
		},
		TEMPLATE: {
			ACTIONS: {
				CREATE_TEMPLATE: "CREATE_TEMPLATE",
				GET_ALL_TEMPLATE: "GET_ALL_TEMPLATE",
				GET_TEMPLATE: "GET_TEMPLATE",
				UPDATE_TEMPLATE: "UPDATE_TEMPLATE",
				DELETE_TEMPLATE: "DELETE_TEMPLATE",
				USER_LOGIN: "USER_LOGIN",
				USER_LOGOUT: "USER_LOGOUT",
				USER_REGISTRATION: "USER_REGISTRATION",
				PASSWORD_UPDATE: "PASSWORD_UPDATE",
			},
			DESCRIPTIONS: {
				TEMPLATE_CREATED: "Created new template",
				TEMPLATE_UPDATED: "Updated template",
				TEMPLATE_DELETED: "Deleted template",
				TEMPLATE_RETRIEVED: "Retrieved template details",
				TEMPLATES_RETRIEVED: "Retrieved template list",
				USER_LOGGED_IN: "User logged in",
				USER_LOGGED_OUT: "User logged out",
				USER_REGISTERED: "User registered",
				PASSWORD_CHANGED: "Password changed",
			},
			PAGES: {
				TEMPLATE_CREATION: "Template Creation",
				TEMPLATE_UPDATE: "Template Update",
				TEMPLATE_DELETION: "Template Deletion",
				TEMPLATE_DETAILS: "Template Details",
				TEMPLATE_LIST: "Template List",
				USER_LOGIN: "User Login",
				USER_REGISTRATION: "User Registration",
				PASSWORD_CHANGE: "Password Change",
			},
		},
	},

	AUDIT_LOG: {
		ACTIONS: {
			CREATE: "CREATE",
			READ: "READ",
			UPDATE: "UPDATE",
			DELETE: "DELETE",
			LOGIN: "LOGIN",
			LOGOUT: "LOGOUT",
			REGISTER: "REGISTER",
		},
		RESOURCES: {
			TEMPLATE: "templates",
			USERS: "users",
			ORGANIZATIONS: "organizations",
			AUTH: "auth",
			PRODUCTS: "products",
			PURCHASE: "purchase",
			CATEGORY: "category",
			WISHLISTITEM: "wishlistitem",
			CARTITEM: "cartitem",
			ORDER: "order",
			ORDERITEM: "orderitem",
			VENDOR: "vendor",
			INSTALLMENT: "installment",
			NOTIFICATION: "notification",
		},
		SEVERITY: {
			LOW: "LOW" as const,
			MEDIUM: "MEDIUM" as const,
			HIGH: "HIGH" as const,
			CRITICAL: "CRITICAL" as const,
		},
		ENTITY_TYPES: {
			TEMPLATE: "template",
			USER: "user",
			ORGANIZATION: "organization",
			PRODUCTS: "products",
			PURCHASE: "purchase",
			CATEGORY: "category",
			WISHLISTITEM: "wishlistitem",
			CARTITEM: "cartitem",
			ORDER: "order",
			ORDERITEM: "orderitem",
			VENDOR: "vendor",
			INSTALLMENT: "installment",
			NOTIFICATION: "notification",
		},
		PRODUCTS: {
			DESCRIPTIONS: {
				PRODUCTS_CREATED: "Created new products",
				PRODUCTS_UPDATED: "Updated products",
				PRODUCTS_DELETED: "Deleted products",
			},
		},
		PURCHASE: {
			DESCRIPTIONS: {
				PURCHASE_CREATED: "Created new purchase",
				PURCHASE_UPDATED: "Updated purchase",
				PURCHASE_DELETED: "Deleted purchase",
			},
		},
		CATEGORY: {
			DESCRIPTIONS: {
				CATEGORY_CREATED: "Created new category",
				CATEGORY_UPDATED: "Updated category",
				CATEGORY_DELETED: "Deleted category",
			},
		},
		WISHLISTITEM: {
			DESCRIPTIONS: {
				WISHLISTITEM_CREATED: "Created new wishlistitem",
				WISHLISTITEM_UPDATED: "Updated wishlistitem",
				WISHLISTITEM_DELETED: "Deleted wishlistitem",
			},
		},
		CARTITEM: {
			DESCRIPTIONS: {
				CARTITEM_CREATED: "Created new cartitem",
				CARTITEM_UPDATED: "Updated cartitem",
				CARTITEM_DELETED: "Deleted cartitem",
			},
		},
		ORDER: {
			DESCRIPTIONS: {
				ORDER_CREATED: "Created new order",
				ORDER_UPDATED: "Updated order",
				ORDER_DELETED: "Deleted order",
			},
		},
		ORDERITEM: {
			DESCRIPTIONS: {
				ORDERITEM_CREATED: "Created new orderitem",
				ORDERITEM_UPDATED: "Updated orderitem",
				ORDERITEM_DELETED: "Deleted orderitem",
			},
		},
		VENDOR: {
			DESCRIPTIONS: {
				VENDOR_CREATED: "Created new vendor",
				VENDOR_UPDATED: "Updated vendor",
				VENDOR_DELETED: "Deleted vendor",
			},
		},
		INSTALLMENT: {
			DESCRIPTIONS: {
				INSTALLMENT_CREATED: "Created new installment",
				INSTALLMENT_UPDATED: "Updated installment",
				INSTALLMENT_DELETED: "Deleted installment",
			},
		},
		NOTIFICATION: {
			DESCRIPTIONS: {
				NOTIFICATION_CREATED: "Created new notification",
				NOTIFICATION_UPDATED: "Updated notification",
				NOTIFICATION_DELETED: "Deleted notification",
			},
		},

		TEMPLATE: {
			DESCRIPTIONS: {
				TEMPLATE_CREATED: "Created new template",
				TEMPLATE_UPDATED: "Updated template",
				TEMPLATE_DELETED: "Deleted template",
				USER_CREATED: "Created new user",
				USER_UPDATED: "Updated user",
				USER_DELETED: "Deleted user",
				USER_LOGGED_IN: "User logged in",
				USER_LOGGED_OUT: "User logged out",
			},
		},
	},
};
