import { z } from "zod";
import { isValidObjectId } from "mongoose";

// Enums
export const OrderStatusEnum = z.enum([
	"PENDING_APPROVAL",
	"APPROVED",
	"REJECTED",
	"PROCESSING",
	"SHIPPED",
	"DELIVERED",
	"CANCELLED",
	"RETURNED",
]);

export const PaymentMethodEnum = z.enum([
	"PAYROLL_DEDUCTION",
	"CASH",
	"CREDIT_CARD",
	"DEBIT_CARD",
	"BANK_TRANSFER",
	"OTHER",
]);

export const PaymentStatusEnum = z.enum([
	"PENDING",
	"PROCESSING",
	"COMPLETED",
	"FAILED",
	"REFUNDED",
]);

export const PaymentTypeEnum = z.enum(["CASH", "INSTALLMENT", "POINTS", "MIXED"]);

export type OrderStatus = z.infer<typeof OrderStatusEnum>;
export type PaymentMethod = z.infer<typeof PaymentMethodEnum>;
export type PaymentStatus = z.infer<typeof PaymentStatusEnum>;
export type PaymentType = z.infer<typeof PaymentTypeEnum>;

// Decimal schema helper (for Prisma Float type)
const decimalSchema = z
	.union([z.string().regex(/^\d+\.?\d*$/, "Invalid decimal format"), z.number()])
	.transform((val) => {
		if (typeof val === "string") {
			return parseFloat(val);
		}
		return val;
	});

// Order Item input schema (request). These will be stored in OrderItem collection.
export const OrderItemInputSchema = z.object({
	itemId: z.string().refine((val) => isValidObjectId(val), {
		message: "Invalid itemId ObjectId format",
	}),
	quantity: z.number().int().min(1, "Quantity must be at least 1"),
	unitPrice: decimalSchema.optional(), // Optional, will be fetched from item.sellingPrice if not provided
	discount: decimalSchema.optional(), // Optional, will be calculated from item if not provided
	subtotal: decimalSchema.optional(), // Optional, will be calculated
});

const OrderItemInputArraySchema = z
	.array(OrderItemInputSchema)
	.min(1, "Order must have at least one item");

// OrderItem output is stored in OrderItem model; see `zod/orderItem.zod.ts`.

// Order Schema (full, including ID)
export const OrderSchema = z.object({
	id: z.string().refine((val) => isValidObjectId(val), {
		message: "Invalid ObjectId format",
	}),
	orderNumber: z.string().min(1, "Order number is required"),
	userId: z.string().refine((val) => isValidObjectId(val), {
		message: "Invalid userId ObjectId format",
	}),
	status: OrderStatusEnum.default("PENDING_APPROVAL"),
	subtotal: decimalSchema,
	discount: decimalSchema.default(0),
	tax: decimalSchema.default(0),
	total: decimalSchema,
	paymentType: PaymentTypeEnum.default("INSTALLMENT"),
	installmentMonths: z.number().int().optional().nullable(),
	installmentCount: z.number().int().optional().nullable(),
	installmentAmount: decimalSchema.optional().nullable(),
	pointsUsed: decimalSchema.optional().nullable(),
	trackingNumber: z.string().optional().nullable(),
	paymentMethod: PaymentMethodEnum.default("PAYROLL_DEDUCTION"),
	paymentStatus: PaymentStatusEnum.default("PENDING"),
	orderDate: z.coerce.date(),
	shippedDate: z.coerce.date().optional().nullable(),
	deliveredDate: z.coerce.date().optional().nullable(),
	cancelledDate: z.coerce.date().optional().nullable(),
	notes: z.string().optional().nullable(),
	createdAt: z.coerce.date(),
	updatedAt: z.coerce.date(),
});

export type Order = z.infer<typeof OrderSchema>;

// Create Order Schema (excluding ID, createdAt, updatedAt)
// Items use OrderItemInputSchema (without required discount/subtotal)
// All calculated fields (subtotal, discount, tax, total) are optional
// Note: orderNumber is auto-generated by the controller, not provided in request body
// userId = SSO user id (from ADAM); replaces legacy employeeId
export const CreateOrderSchema = z
	.object({
		userId: z.string().refine((val) => isValidObjectId(val), {
			message: "Invalid userId ObjectId format",
		}),
		status: OrderStatusEnum.optional(),
		// Accept either `items` (legacy) or `orderItems` (preferred). Controller uses `items` after transform.
		items: OrderItemInputArraySchema.optional(),
		orderItems: OrderItemInputArraySchema.optional(),
		subtotal: decimalSchema.optional(), // Will be calculated
		discount: decimalSchema.optional(), // Will be calculated
		tax: decimalSchema.optional(), // Will be calculated
		total: decimalSchema.optional(), // Will be calculated
		paymentType: PaymentTypeEnum.optional(),
		/** Number of installments (e.g. 3, 6, 12). 3 = 1.5 months bi-monthly, 6 = 3 months. Replaces installmentMonths in API. */
		installments: z
			.number()
			.int()
			.min(1, "Installments must be at least 1")
			.max(24)
			.optional()
			.nullable(),
		installmentMonths: z.number().int().optional().nullable(), // deprecated: use installments
		installmentCount: z.number().int().optional().nullable(),
		installmentAmount: decimalSchema.optional().nullable(),
		pointsUsed: decimalSchema.optional().nullable(),
		trackingNumber: z.string().optional().nullable(),
		paymentMethod: PaymentMethodEnum.optional(),
		paymentStatus: PaymentStatusEnum.optional(),
		orderDate: z.coerce.date().optional(),
		shippedDate: z.coerce.date().optional().nullable(),
		deliveredDate: z.coerce.date().optional().nullable(),
		cancelledDate: z.coerce.date().optional().nullable(),
		notes: z.string().optional().nullable(),
		organizationId: z
			.string()
			.refine((val) => !val || isValidObjectId(val), {
				message: "Invalid organizationId ObjectId format",
			})
			.optional()
			.nullable(),
	})
	.superRefine((val, ctx) => {
		const hasItems = Array.isArray(val.items) && val.items.length > 0;
		const hasOrderItems = Array.isArray(val.orderItems) && val.orderItems.length > 0;

		if (!hasItems && !hasOrderItems) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				path: ["items"],
				message: "Order must have at least one item",
			});
		}
		if (hasItems && hasOrderItems) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				path: ["orderItems"],
				message: "Provide either items or orderItems, not both",
			});
		}
		// Reject duplicate itemIds (same item should appear once with combined quantity)
		const itemList = val.items ?? val.orderItems ?? [];
		const itemIds = itemList.map((i: { itemId: string }) => i.itemId);
		const duplicates = itemIds.filter(
			(id, index) => itemIds.indexOf(id) !== index,
		);
		const uniqueDuplicates = [...new Set(duplicates)];
		if (uniqueDuplicates.length > 0) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				path: ["items"],
				message: `Duplicate item IDs not allowed: ${uniqueDuplicates.join(", ")}. Use a single line per item with the total quantity.`,
			});
		}
	})
	.transform((val) => ({
		...val,
		items: (val.items ?? val.orderItems) as z.infer<typeof OrderItemInputArraySchema>,
	}));

export type CreateOrder = z.infer<typeof CreateOrderSchema>;

// Update Order Schema (partial, excluding immutable fields)
export const UpdateOrderSchema = OrderSchema.omit({
	id: true,
	createdAt: true,
	updatedAt: true,
}).partial();

export type UpdateOrder = z.infer<typeof UpdateOrderSchema>;
